kind: PersistentVolume
apiVersion: v1
metadata:
  name: expense-efs
spec:
  storageClassName: ""
  PersistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00d22d840500068ff