kind: PersistentVolume
apiVersion: v1
metadata:
  name: expense-efs
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00d22d840500068ff
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: expense-efs
spec:
  storageClassName: ""
  volumeName: expense-efs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: efs-static
  labels:
    purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: expense-efs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: expense-efs
    persistentVolumeClaim:
      claimName: expense-efs
---
kind: Service
apiVersion: v1
metadata:
  name: efs-static
spec:
  type: NodePort
  selector:
    purpose: efs-static
  ports:
  - name: efs-static-ngnix
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30021