kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-dynamic
spec:
  storageClassName: "efs-expense"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-dynamic
    persistentVolumeClaim:
      claimName: efs-dynamic
---
kind: Service
apiVersion: v1
metadata:
  name: efs-dynamic
spec:
  type: NodePort
  selector:
    purpose: efs-dynamic
  ports:
  - name: efs-dynamic-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30022